// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Clanstvo.DataAccess.SqlServer.Data.DbModels
{
    public partial class ClanRangStarost
    {
        [Key]
        public int ClanId { get; set; }
        [Key]
        public int RangStarostId { get; set; }
        [Column(TypeName = "date")]
        public DateTime Datum { get; set; }

        [ForeignKey("ClanId")]
        [InverseProperty("ClanRangStarost")]
        public virtual Clan Clan { get; set; }
        [ForeignKey("RangStarostId")]
        [InverseProperty("ClanRangStarost")]
        public virtual RangStarost RangStarost { get; set; }
    }
}