// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Clanstvo.DataAccess.SqlServer.Data.DbModels
{
    public partial class Clan
    {
        public Clan()
        {
            ClanRangStarost = new HashSet<ClanRangStarost>();
            ClanRangZasluga = new HashSet<ClanRangZasluga>();
            Clanarina = new HashSet<Clanarina>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string Ime { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string Prezime { get; set; }
        [Column(TypeName = "date")]
        public DateTime DatumRodenja { get; set; }
        public byte[] Slika { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string Adresa { get; set; }
        public bool ImaMaramu { get; set; }
        [Column(TypeName = "date")]
        public DateTime? DatumMarama { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string MjestoMarama { get; set; }

        [InverseProperty("Clan")]
        public virtual ICollection<ClanRangStarost> ClanRangStarost { get; set; }
        [InverseProperty("Clan")]
        public virtual ICollection<ClanRangZasluga> ClanRangZasluga { get; set; }
        [InverseProperty("Clan")]
        public virtual ICollection<Clanarina> Clanarina { get; set; }
    }
}