// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Clanstvo.DataAccess.SqlServer.Data.DbModels
{
    public partial class ClanRangZasluga
    {
        [Key]
        public int ClanId { get; set; }
        [Key]
        public int RangZaslugaId { get; set; }
        [Column(TypeName = "date")]
        public DateTime Datum { get; set; }

        [ForeignKey("ClanId")]
        [InverseProperty("ClanRangZasluga")]
        public virtual Clan Clan { get; set; }
        [ForeignKey("RangZaslugaId")]
        [InverseProperty("ClanRangZasluga")]
        public virtual RangZasluga RangZasluga { get; set; }
    }
}