// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Clanstvo.DataAccess.SqlServer.Data.DbModels;

namespace Clanstvo.DataAccess.SqlServer.Data
{ 
    public partial class ClanstvoContext : DbContext
    {
        public ClanstvoContext()
        {
        }

        public ClanstvoContext(DbContextOptions<ClanstvoContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Clan> Clan { get; set; }
        public virtual DbSet<ClanRangStarost> ClanRangStarost { get; set; }
        public virtual DbSet<ClanRangZasluga> ClanRangZasluga { get; set; }
        public virtual DbSet<Clanarina> Clanarina { get; set; }
        public virtual DbSet<RangStarost> RangStarost { get; set; }
        public virtual DbSet<RangZasluga> RangZasluga { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<ClanRangStarost>(entity =>
            {
                entity.HasKey(e => new { e.ClanId, e.RangStarostId })
                    .HasName("PK_ClanRangStar");

                entity.HasOne(d => d.Clan)
                    .WithMany(p => p.ClanRangStarost)
                    .HasForeignKey(d => d.ClanId)
                    .HasConstraintName("FK_ClanRangStar_Clanovi");

                entity.HasOne(d => d.RangStarost)
                    .WithMany(p => p.ClanRangStarost)
                    .HasForeignKey(d => d.RangStarostId)
                    .HasConstraintName("FK_ClanRangStar_RangStar");
            });

            modelBuilder.Entity<ClanRangZasluga>(entity =>
            {
                entity.HasKey(e => new { e.ClanId, e.RangZaslugaId })
                    .HasName("PK_ClanRangZasl");

                entity.HasOne(d => d.Clan)
                    .WithMany(p => p.ClanRangZasluga)
                    .HasForeignKey(d => d.ClanId)
                    .HasConstraintName("FK_ClanRangZasl_Clanovi");

                entity.HasOne(d => d.RangZasluga)
                    .WithMany(p => p.ClanRangZasluga)
                    .HasForeignKey(d => d.RangZaslugaId)
                    .HasConstraintName("FK_ClanRangZasl_RangZasl");
            });

            modelBuilder.Entity<Clanarina>(entity =>
            {
                entity.HasOne(d => d.Clan)
                    .WithMany(p => p.Clanarina)
                    .HasForeignKey(d => d.ClanId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Clanarine_Clanovi");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}